---
version: v1.0.0
server:
  port: 8080
  health_check_port: 80
  health_check_path: /healthz
  timeout: 10s
  shutdown_duration: 5s
  tls:
    enabled: true
    cert: _cert_
    key: _key_
    ca: _ca_
token:
  athenz_domain:  _athenz_domain_
  service_name: _service_name_
  ntoken_path: ""
  private_key_path: _athenz_private_key_
  validate_token: false
  refresh_duration: 30m
  key_version: v1.0
  expiration: 20m
udb:
  url: https://api.udb.yahoo.co.jp:4443/v2/users
hcc:
  hostname: auction.zcp.athenz.corp.yahoo.co.jp
  ip: 172.16.23.222
proxy:
  auth_header: Athenz-Principal-Auth
  buffer_size: 1024

